version: '3'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  prometheus:
    container_name: prometheus-goexpert
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./client/.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./client/.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension      
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension      
    depends_on:
      - jaeger-all-in-one   

  grafana:
    container_name: grafana-goexpert
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  client:
    container_name: rate-limiter-goexpert
    build:
      context: .
    environment:
      - TITLE=Microservice Demo
      - CONTENT=This is a demo of a microservice
      - EXTERNAL_CALL_URL=http://weather-otel-server:8181
      - EXTERNAL_CALL_METHOD=GET
      - REQUEST_NAME_OTEL=microservice-client-request
      - OTEL_SERVICE_NAME=microservice-client
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_REQUEST_IP_TPS=10
      - HTTP_REQUEST_APIKEY_TPS=10      
      - HTTP_REQUEST_TIME_BLOCK=5s
      - HTTP_PORT=:8080
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector
volumes:
  cache:
    driver: local

